### PR TITLE
Added diagram of Fragment into Activity integration via Fragment Manager

### PR DESCRIPTION
**Pull request by OleksandrKucherenko**

### CODE REVIEW

**Comment by OleksandrKucherenko** [comment]
who can merge this?!

**Comment by OleksandrKucherenko** [comment]
Why its not merged and was simply closed?!

**Comment by OleksandrKucherenko** [comment]
@xxv ^ can we merge this?

**Comment by xxv** [comment]
Sorry for the extremely long delay. I burned out on doing Android dev. some years back and I didn't have the spoons to verify PRs.

Could you add in a date to your diagram? That way someone can, at a glance, see what state of the world it is referring to and make some guesses if it's out of date or not.

Also, a link to external hosting seems unnecessary, as hosting files on Github works perfectly well.

**Comment by OleksandrKucherenko** [comment]
5 years... Looks like you was very busy 👍

**Comment by xxv** [comment]
> 5 years... Looks like you was very busy

I'm sure that if/when you burn out on a particular technology, you'll look at PRs talking about extremely nuanced elements of that technology with the same dread I did.

**Comment by xxv** [comment]
And to be clear, I'll happily merge this PR (I can't verify any of the technical details, but you appear to be an expert). I mostly just think a date may be nice, as it's so easy to lose track of how old technical diagrams are, especially when people copy/paste/download them divorced from their original source.

**Comment by OleksandrKucherenko** [comment]
> And to be clear, I'll happily merge this PR (I can't verify any of the technical details, but you appear to be an expert). I mostly just think a date may be nice, as it's so easy to lose track of how old technical diagrams are, especially when people copy/paste/download them divorced from their original source.

On diagram (in legend) placed that its about android support library. Which is today known as AndroidX... I think legend title is enough for other developers to understand the version context. 

p.s. how I know fragments states logic is still the same. changed only package names of the classes.

**Comment by xxv** [comment]
Ok, cool. I'll go with your intuition on this. Thanks for your contribution. Merged.

**Pull request closed without merging**
